INFO:2019-02-26 10:07:19,705:Asyncioimsender.py:89:Try to connect:<socket.socket fd=4, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 39822), raddr=('127.0.0.1', 8888)>
INFO:2019-02-26 10:07:19,706:Asyncioimsender.py:141:Acitve:RUSTED_CA_FILE:/media/acer/临时文件/python/Pytest/IM/trustedCA/CAfile.pem:TRUSTED_CA:/media/acer/临时文件/python/Pytest/IM/trustedCA
INFO:2019-02-26 10:07:19,707:Asyncioimsender.py:149:MY_CA:/media/acer/临时文件/python/Pytest/IM/myCA/myCA.crt:MY_CA_KEY:/media/acer/临时文件/python/Pytest/IM/myCA/myA.key:key:1234
ERROR:2019-02-26 10:07:19,707:Asyncioimsender.py:302:socket creation Failure:[Errno 2] No such file or directory
INFO:2019-02-26 10:10:33,795:Asyncioimsender.py:89:Try to connect:<socket.socket fd=4, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 39824), raddr=('127.0.0.1', 8888)>
INFO:2019-02-26 10:10:33,796:Asyncioimsender.py:141:Acitve:RUSTED_CA_FILE:/media/acer/临时文件/python/Pytest/IM/trustedCA/CAfile.pem:TRUSTED_CA:/media/acer/临时文件/python/Pytest/IM/trustedCA
INFO:2019-02-26 10:10:33,797:Asyncioimsender.py:149:MY_CA:/media/acer/临时文件/python/Pytest/IM/myCA/myCA.crt:MY_CA_KEY:/media/acer/临时文件/python/Pytest/IM/myCA/myA.key:key:1234
ERROR:2019-02-26 10:10:33,797:Asyncioimsender.py:302:socket creation Failure:[Errno 2] No such file or directory
INFO:2019-02-26 10:13:48,740:Asyncioimsender.py:90:Try to connect:<socket.socket fd=4, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 39826), raddr=('127.0.0.1', 8888)>
INFO:2019-02-26 10:13:48,741:Asyncioimsender.py:142:Acitve:RUSTED_CA_FILE:/media/acer/临时文件/python/Pytest/IM/trustedCA/CAfile.pem:TRUSTED_CA:/media/acer/临时文件/python/Pytest/IM/trustedCA
INFO:2019-02-26 10:13:48,742:Asyncioimsender.py:150:MY_CA:/media/acer/临时文件/python/Pytest/IM/myCA/myCA.crt:MY_CA_KEY:/media/acer/临时文件/python/Pytest/IM/myCA/myA.key:key:1234
ERROR:2019-02-26 10:13:48,742:Asyncioimsender.py:303:socket creation Failure:[Errno 2] No such file or directory
INFO:2019-02-26 10:24:08,521:Asyncioimsender.py:89:Try to connect:<socket.socket fd=4, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 39828), raddr=('127.0.0.1', 8888)>
INFO:2019-02-26 10:24:08,522:Asyncioimsender.py:141:Acitve:RUSTED_CA_FILE:/media/acer/临时文件/python/Pytest/IM/trustedCA/CAfile.pem:TRUSTED_CA:/media/acer/临时文件/python/Pytest/IM/trustedCA
INFO:2019-02-26 10:24:08,523:Asyncioimsender.py:149:MY_CA:/media/acer/临时文件/python/Pytest/IM/myCA/myCA.crt:MY_CA_KEY:/media/acer/临时文件/python/Pytest/IM/myCA/myCA.key:key:1234
DEBUG:2019-02-26 10:24:08,531:Asyncioimsender.py:154:wrapp peersock finished
INFO:2019-02-26 10:24:08,531:Asyncioimsender.py:95:Connect succeeds:SSL:receiver
INFO:2019-02-26 10:26:11,422:Asyncioimsender.py:89:Try to connect:<socket.socket fd=4, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 39830), raddr=('127.0.0.1', 8888)>
INFO:2019-02-26 10:26:11,423:Asyncioimsender.py:141:Acitve:RUSTED_CA_FILE:/media/acer/临时文件/python/Pytest/IM/trustedCA/CAfile.pem:TRUSTED_CA:/media/acer/临时文件/python/Pytest/IM/trustedCA
INFO:2019-02-26 10:26:11,423:Asyncioimsender.py:149:MY_CA:/media/acer/临时文件/python/Pytest/IM/myCA/myCA.crt:MY_CA_KEY:/media/acer/临时文件/python/Pytest/IM/myCA/myCA.key:key:1234
DEBUG:2019-02-26 10:26:11,431:Asyncioimsender.py:154:wrapp peersock finished
INFO:2019-02-26 10:26:11,431:Asyncioimsender.py:95:Connect succeeds:SSL:receiver
